### ISSUE TITLE
[BUG] Error on iOS when run from source

### ISSUE THREAD

**Issue by heinekenpsx** [permasigner/permasigner#82] opened 2022-09-01 06:34 UTC
xXx:~/permasigner root# 3python3 main.py -p /var
/mobile/CloneApp/Appcake_7.2.2-Fix.ipa
Permasigner | Version 1.1.2_main_445bbbc
Program created by Nebula and supernova | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] Checking for dependencies...

[*] Extracting IPA
Reading plist...

[*] Making deb directories...
Copying control file and maintainer scripts...
Changing deb file scripts permissions...
Copying application bundle...
Changing app executable permissions...

[*] Signing bundle with ldid...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    __main__.main(False)
  File "/private/var/mobile/permasigner/permasigner/__main__.py", line 52, in main
    ps.main()
  File "/private/var/mobile/permasigner/permasigner/permasigner.py", line 96, in main
    out_dir = self.permasign()
  File "/private/var/mobile/permasigner/permasigner/permasigner.py", line 187, in permasign
    signer.sign_with_ldid(self.ldid)
  File "/private/var/mobile/permasigner/permasigner/sign.py", line 183, in sign_with_ldid
    stdout=subprocess.DEVNULL)
  File "/usr/local/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 1] Operation not permitted: '/var/mobile/.permasigner/ldid'

**Comment by superrnovae** [comment] 2022-09-01 06:53
Does it work if you run it as user?

**Comment by heinekenpsx** [comment] 2022-09-01 06:56
> Have you tried running it as user, not root? Does the issue persist?

Still same error

**Comment by superrnovae** [comment] 2022-09-01 07:04
> > Have you tried running it as user, not root? Does the issue persist?
> 
> Still same error

Manually remove ldid from .permasigner directory and rerun the script.

**Comment by superrnovae** [comment] 2022-09-01 07:11
> > > > Have you tried running it as user, not root? Does the issue persist?
> 
> > > 
> 
> > > 
> 
> > > Still same error
> 
> > 
> 
> > Manually remove ldid from .permasigner directory and rerun the script as normal user.
> 
> 
> 
> Not working, it will check for depend and automatically download a ldid file

I can't reproduce it on my iPad. Please, attach the logs.

**Comment by heinekenpsx** [comment] 2022-09-01 07:12
> > > > > Have you tried running it as user, not root? Does the issue persist?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Still same error
> > 
> > 
> > > 
> > 
> > 
> > > Manually remove ldid from .permasigner directory and rerun the script as normal user.
> > 
> > 
> > Not working, it will check for depend and automatically download a ldid file
> 
> I can't reproduce it on my iPad. Please, attach the logs.

My mistake, tried as user and this is the log
xXx:~ root# exit
exit
xXx:~ mobile$ cd permasigner/
xXx:~/permasigner mobile$ 3python3 main.py -p /v
ar/mobile/CloneApp/Appcake_7.2.2-Fix.ipa
Permasigner | Version 1.1.2_main_445bbbc
Program created by Nebula and supernova | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] Checking for dependencies...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    __main__.main(False)
  File "/private/var/mobile/permasigner/permasigner/__main__.py", line 52, in main
    ps.main()
  File "/private/var/mobile/permasigner/permasigner/permasigner.py", line 70, in main
    Ldid(self.data_dir, self.args).download()
  File "/private/var/mobile/permasigner/permasigner/sign.py", line 152, in download
    self.save_file(content)
  File "/private/var/mobile/permasigner/permasigner/sign.py", line 91, in save_file
    with open(ldid_name, "wb") as f:
PermissionError: [Errno 13] Permission denied: 'ldid'
xXx:~/permasigner mobile$

**Comment by superrnovae** [comment] 2022-09-01 07:15
Remove .permasigner directory. I assume only root user can write to it, since it was created by the script run as root.

**Comment by heinekenpsx** [comment] 2022-09-01 07:24
> Remove .permasigner directory. I assume only root user can write to it, since it was created by the script ran as root.

Same eror :(
I think it still requires ldid
I have another question that git pull can't run as user ?
xXx:~ root# exit
exit
xXx:~ mobile$ cd permasigner/
xXx:~/permasigner mobile$ git pull
error: cannot open .git/FETCH_HEAD: Permission denied
xXx:~/permasigner mobile$

**Comment by superrnovae** [comment] 2022-09-01 07:25
You've cloned the repository as root user too.

**Comment by superrnovae** [comment] 2022-09-01 07:27
> I think it still requires ldid

It does require ldid, it can't save it to .permasigner directory, because it does not have write permission.

You must not run the script as root. You also must not clone repositories as root. Run everything as normal user and it'll work.

**Comment by heinekenpsx** [comment] 2022-09-01 07:35
Still not working, .permasigner directory is still created, when it checks depend, it connects to the network and downloads the ldld file
xXx:~ root# exit 
exit
xXx:~ mobile$ git clone https://github.com/perma
signer/permasigner
Cloning into 'permasigner'...
remote: Enumerating objects: 2159, done.
remote: Counting objects: 100% (195/195), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 2159 (delta 122), reused 117 (delta 65), pack-reused 1964
Receiving objects: 100% (2159/2159), 547.89 KiB | 1.72 MiB/s, done.
Resolving deltas: 100% (1425/1425), done.
xXx:~ mobile$ cd permasigner/
xXx:~/permasigner mobile$ 3python3 main.py -p /v
ar/mobile/CloneApp/Appcake_7.2.2-Fix.ipa
Permasigner | Version 1.1.2_main_445bbbc
Program created by Nebula and supernova | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] Checking for dependencies...

[*] Extracting IPA
Reading plist...

[*] Making deb directories...
Copying control file and maintainer scripts...
Changing deb file scripts permissions...
Copying application bundle...
Changing app executable permissions...

[*] Signing bundle with ldid...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    __main__.main(False)
  File "/private/var/mobile/permasigner/permasigner/__main__.py", line 52, in main
    ps.main()
  File "/private/var/mobile/permasigner/permasigner/permasigner.py", line 96, in main
    out_dir = self.permasign()
  File "/private/var/mobile/permasigner/permasigner/permasigner.py", line 187, in permasign
    signer.sign_with_ldid(self.ldid)
  File "/private/var/mobile/permasigner/permasigner/sign.py", line 183, in sign_with_ldid
    stdout=subprocess.DEVNULL)
  File "/usr/local/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 1] Operation not permitted: '/var/mobile/.permasigner/ldid'
xXx:~/permasigner mobile$

**Comment by superrnovae** [comment] 2022-09-01 07:37
Please enable `-d` flag and provide full output.

**Comment by heinekenpsx** [comment] 2022-09-01 07:41
Yeah
xXx:~ mobile$ cd permasigner/
xXx:~/permasigner mobile$ 3python3 main.py -p /v
ar/mobile/CloneApp/Appcake_7.2.2-Fix.ipa -d
Permasigner | Version 1.1.2_main_445bbbc
Program created by Nebula and supernova | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] Checking for dependencies...
[DEBUG] ldid not found in PATH, we will download it later if needed
[DEBUG] dpkg-deb not found in PATH, we will use constrictor instead
[DEBUG] Comparing /var/mobile/.permasigner/ldid hash with https://github.com/permasigner/ldid/releases/latest/download/ldid_iphoneos_arm64
[DEBUG] Ldid hash failed to verify, saving newer version
[DEBUG] Wrote file.
[DEBUG] Moved ldid to /var/mobile/.permasigner/ldid

[*] Extracting IPA
Reading plist...

[*] Making deb directories...
Copying control file and maintainer scripts...
Changing deb file scripts permissions...
Copying application bundle...
Changing app executable permissions...

[*] Signing bundle with ldid...
[DEBUG] Running command: /var/mobile/.permasigner/ldid -S/tmp/tmpomzynt9b/entitlements.plist -M -K/private/var/mobile/permasigner/permasigner/data/certificate.p12 -Upassword '/tmp/tmpomzynt9b/deb/Applications/appcakej.app'
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    __main__.main(False)
  File "/private/var/mobile/permasigner/permasigner/__main__.py", line 52, in main
    ps.main()
  File "/private/var/mobile/permasigner/permasigner/permasigner.py", line 96, in main
    out_dir = self.permasign()
  File "/private/var/mobile/permasigner/permasigner/permasigner.py", line 187, in permasign
    signer.sign_with_ldid(self.ldid)
  File "/private/var/mobile/permasigner/permasigner/sign.py", line 183, in sign_with_ldid
    stdout=subprocess.DEVNULL)
  File "/usr/local/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 1] Operation not permitted: '/var/mobile/.permasigner/ldid'

**Comment by superrnovae** [comment] 2022-09-01 08:29
Can you manually run ldid from /var/mobile/.permasigner directory? Does it show the same error?

**Comment by heinekenpsx** [comment] 2022-09-01 08:46
> Could you manually run ldid from /var/mobile/.permasigner directory? Does it show the same error?
> 
> `cd /var/mobile/.permasigner/` and `./ldid`

It works normally
xXx:~ mobile$ cd ./permasigner/
xXx:~/permasigner mobile$ cd -
/var/mobile
xXx:~ mobile$ cd .permasigner/
xXx:~/.permasigner mobile$ ./ldid 
Link Identity Editor 

Usage: ./ldid [-Acputype:subtype] [-a] [-C[adhoc | enforcement | expires | hard |
            host | kill | library-validation | restrict | runtime]] [-D] [-d]
            [-Enum:file] [-e] [-H[sha1 | sha256]] [-h] [-Iname]
            [-Kkey.p12 [-Upassword]] [-M] [-P[num]] [-Qrequirements.xml] [-q]
            [-r | -Sfile.xml | -s] [-u] [-arch arch_type] file ...
Common Options:
   -S[file.xml]  Pseudo-sign using the entitlements in file.xml
   -Kkey.p12     Sign using private key in key.p12
   -Upassword    Use password to unlock key.p12
   -M            Merge entitlements with any existing
   -h            Print CDHash of file

More information: 'man ldid'

**Comment by superrnovae** [comment] 2022-09-01 09:39
> > Could you manually run ldid from /var/mobile/.permasigner directory? Does it show the same error?
> > `cd /var/mobile/.permasigner/` and `./ldid`
> 
> It works normally xXx:~ mobile$ cd ./permasigner/ xXx:~/permasigner mobile$ cd - /var/mobile xXx:~ mobile$ cd .permasigner/ xXx:~/.permasigner mobile$ ./ldid Link Identity Editor
> 
> Usage: ./ldid [-Acputype:subtype] [-a] [-C[adhoc | enforcement | expires | hard | host | kill | library-validation | restrict | runtime]] [-D] [-d] [-Enum:file] [-e] [-H[sha1 | sha256]] [-h] [-Iname] [-Kkey.p12 [-Upassword]] [-M] [-P[num]] [-Qrequirements.xml] [-q] [-r | -Sfile.xml | -s] [-u] [-arch arch_type] file ... Common Options: -S[file.xml] Pseudo-sign using the entitlements in file.xml -Kkey.p12 Sign using private key in key.p12 -Upassword Use password to unlock key.p12 -M Merge entitlements with any existing -h Print CDHash of file
> 
> More information: 'man ldid'

well, this is weird.

**Comment by heinekenpsx** [comment] 2022-09-01 10:27
@superrnovae Because of problems related to Eculubratus bootstrap, you have to develop another ldid file? Is there a way for permasigner to browse the ldid file in /usr/libexec ? I want to test your file, copy it to /usr/libexec and see if it works.

**Comment by superrnovae** [comment] 2022-09-01 10:31
> Because of problems related to Eculubratus bootstrap, you have to develop another ldid file?

Yes, elucubratus ldid does not support password protected certificates and can't merge entitlements.

**Comment by superrnovae** [comment] 2022-09-01 10:34
> @superrnovae Because of problems related to Eculubratus bootstrap, you have to develop another ldid file? Is there a way for permasigner to browse the ldid file in /usr/libexec ? I want to test your file, copy it to /usr/libexec and see if it works.

Could you please run `git fetch -a` and then `git checkout subprocess`. Then run the script.

**Comment by heinekenpsx** [comment] 2022-09-01 11:15
> Could you please run `git fetch -a` and then `git checkout subprocess`. Then run the script.

Run the above commands as mobile user?
P/s : I checked that ldid exists in /usr/libexec not /usr/local/bin

**Comment by superrnovae** [comment] 2022-09-01 11:20
> Run the above commands as mobile user?

yes.

**Comment by heinekenpsx** [comment] 2022-09-01 11:27
@superrnovae it works, thanks
xXx:~ mobile$ cd permasigner/
xXx:~/permasigner mobile$ git fetch -a
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (10/10), done
remote: Total 25 (delta 15), reused 25 (delta 15), pack-reused 0
Unpacking objects: 100% (25/25), done.
From https://github.com/permasigner/permasigner
   445bbbc..91b6994  main       -> origin/main
 * [new branch]      subprocess -> origin/subprocess
xXx:~/permasigner mobile$ git checkout subproces
s
Branch 'subprocess' set up to track remote branch 'subprocess' from 'origin'.
Switched to a new branch 'subprocess'
xXx:~/permasigner mobile$ 3python3 main.py -p /v
ar/mobile/CloneApp/Appcake_7.2.2-Fix.ipa
Permasigner | Version 1.1.2_subprocess_64b3b3d
Program created by Nebula and supernova | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] Checking for dependencies...

[*] Extracting IPA
Reading plist...

[*] Making deb directories...
Copying control file and maintainer scripts...
Changing deb file scripts permissions...
Copying application bundle...
Changing app executable permissions...

[*] Signing bundle with ldid...

[*] Packaging the deb file...

[*] We are finished!
[*] Copy the newly created deb from the output folder to your jailbroken iDevice and install it!
[*] The app will continue to work when rebooted to stock.
[*] Also, this is free and open source software! Feel free to donate to my Patreon if you enjoy :)
    https://patreon.com/nebulalol
[*] Output file: /private/var/mobile/permasigner/output/appcakej_7.2.2.deb

**Comment by superrnovae** [comment] 2022-09-01 11:32
Could you please rerun it with `-d` flag?

**Comment by heinekenpsx** [comment] 2022-09-01 11:45
@superrnovae xXx:~ mobile$ cd permasigner/
xXx:~/permasigner mobile$ 3python3 main.py -p /v
ar/mobile/Downloads/7plus.ipa -d
Permasigner | Version 1.1.2_subprocess_64b3b3d
Program created by Nebula and supernova | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] Checking for dependencies...
[DEBUG] ldid not found in PATH, we will download it later if needed
[DEBUG] dpkg-deb found!
[DEBUG] Comparing /var/mobile/.permasigner/ldid hash with https://github.com/permasigner/ldid/releases/latest/download/ldid_iphoneos_arm64
[DEBUG] ldid hash successfully verified.

[*] Extracting IPA
Reading plist...

[*] Making deb directories...
Copying control file and maintainer scripts...
Changing deb file scripts permissions...
Copying application bundle...
Changing app executable permissions...
[DEBUG] Settings chmod +x on /tmp/tmp1buru845/deb/Applications/7plus.app/PlugIns/7plus Notifications Extension.appex/7plus Notifications Extension

[*] Signing bundle with ldid...
[DEBUG] Running command: /var/mobile/.permasigner/ldid -S/tmp/tmp1buru845/entitlements.plist -M -K/private/var/mobile/permasigner/permasigner/data/certificate.p12 -Upassword '/tmp/tmp1buru845/deb/Applications/7plus.app'

[*] Packaging the deb file...
[DEBUG] Running command: dpkg-deb -Zxz --root-owner-group -b /tmp/tmp1buru845/deb /private/var/mobile/permasigner/output/7plus_4.31.deb

[*] We are finished!
[*] Copy the newly created deb from the output folder to your jailbroken iDevice and install it!
[*] The app will continue to work when rebooted to stock.
[*] Also, this is free and open source software! Feel free to donate to my Patreon if you enjoy :)
    https://patreon.com/nebulalol
[*] Output file: /private/var/mobile/permasigner/output/7plus_4.31.deb

**Comment by heinekenpsx** [comment] 2022-09-01 11:45
@superrnovae It worked but had 2 problems:
1/ It checks the depend every time, this requires a network connection and consumes a bit of data
2/ The ipa file containing the Frameworks folder still crashes, we've discussed this before

**Comment by superrnovae** [comment] 2022-09-01 11:46
> It checks the depend every time, this requires a network connection and consumes a bit of data

you can pass `-z` flag to skip it.

> The ipa file containing the Frameworks folder still crashes, we've discussed this before

Does this IPA crash? Could you provide links to other IPAs that crash as well so that I can test all of them?

**Comment by heinekenpsx** [comment] 2022-09-01 12:00
@superrnovae yeah, try this :)
https://drive.google.com/file/d/1CI8X0F20pHeS_gQXtpKZNMXix8a5bnsj/view?usp=drivesdk

**Comment by heinekenpsx** [comment] 2022-09-01 12:03
@superrnovae sorry, i've sent an encrypted ipa,
I will try to decrypt it and check more, wait for me

**Comment by heinekenpsx** [comment] 2022-09-01 12:22
@superrnovae well, i actually found the problem, it only works with the decrypted ipa files, but with the encrypted ipa it will crash

**Comment by superrnovae** [comment] 2022-09-01 12:29
> well, i actually found the problem, it only works with the decrypted ipa files, but with the encrypted ipa it will crash

that's how it works. When you sideload with xcode/ios-deploy/altstore the binary will get decrypted by your device. 
In our case, we're installing it directly on device, no decryption is happening.

**Comment by superrnovae** [comment] 2022-09-01 12:30
Fixed in [64b3b3](https://github.com/permasigner/permasigner/commit/64b3b3dd2c20c518ff178d30aa950557526dd01b)

**Closed by superrnovae** 2022-09-01 12:30 UTC
Labels: bug

**Comment by heinekenpsx** [comment] 2022-09-01 16:21
@superrnovae 
I just checked PermasigniOS as deb
https://github.com/powenn/permasigneriOS
The latest deb file was updated 27 days ago, and it actually works on the device using Eculubratus bootstrap (due to my mistake when using encrypted ipa file thinking it didn't work), while Permasigner was update for Eculubratus 7 days ago. I'm wondering if updating ldid really solves the problem??

**Comment by itsnebulalol** [comment] 2022-09-01 16:24
PermasigneriOS doesn’t use an encrypted cert nor merge entitlements I don’t think. Since it doesn’t require procursus ldid, it can use the elucubratus one

**Comment by heinekenpsx** [comment] 2022-09-01 16:27
> PermasigneriOS doesn’t use an encrypted cert nor merge entitlements I don’t think. Since it doesn’t require procursus ldid, it can use the elucubratus one

I thought PermasigniOS was developed based on Permasigner ??

**Comment by itsnebulalol** [comment] 2022-09-01 16:28
Yes, it is. It doesn't change the fact that they have changed stuff.

**Comment by heinekenpsx** [comment] 2022-09-01 16:34
Ok, thank you for your hard work :)

**Comment by superrnovae** [comment] 2022-09-01 16:50
I don't know how permasignerios works, I haven't seen its code. I assume it dumps the entitlements, merges them manually and resigns the bundle. 

We supported elucubratus in the first versions, but dropped the support, because it made more sense to use statically linked ldid from procursus, which guarantees we're signing with the same version on all systems. It also supports encrypted certificates and entitlement merging (unlike ldid from elucubratus). Is maintained and gets regular bug fixes 

The du process was freaking out because of some bug in python 3.7. As you can see we're testing on all systems (macOS, Linux, windows) and the script works flawlessly. I also test on FreeBSD VM and my iPad, and nebula tests on his iPhone. 

So, the issue was not in permasigner, rather in elucubratus. This is why I believe everyone should make a switch to procursus.

**Comment by heinekenpsx** [comment] 2022-09-01 17:14
I think Eculubratus is still good, now permasigner works fine on my device, although sometimes the deb file after installation doesn't appear on home screen, needs some fix and run uicache command
I can also run permasigner commands as root, thanks for your enthusiastic support

**Comment by superrnovae** [comment] 2022-09-01 17:17
> I think Eculubratus is still good, now permasigner works fine on my device, although sometimes the deb file after installation doesn't appear on home screen, needs some fix and run uicache command
> 
> I can also run permasigner commands as root, thanks for your enthusiastic support

Run `apt-get install -f` after dpkg.

**Comment by heinekenpsx** [comment] 2022-09-01 17:34
Do you mean run the above command after successful installation ?

**Comment by superrnovae** [comment] 2022-09-01 19:45
> Do you mean run the above command after successful installation ?

Yes, it's required on elucubratus for the app to appear on the Home Screen.

**Comment by heinekenpsx** [comment] 2022-09-02 00:39
Thanks
